/* =============================================
   Bandhani Australia — products.js
   Edit THIS FILE to add/update products and images.
   Put images in the /images/ folder next to index.html.
   ============================================= */

const PRODUCTS = [
  {
    id: "p001",
    name: "Crimson Gaji Silk Bandhani Saree",
    subtitle: "Pure Gaji Silk · Fine Bandhani Dots",
    description: "Classic Jamnagar Borjaal pattern in vibrant red with ivory dots. Traditional artisan work from the Khatri families of Jamnagar. Suitable for weddings and festive occasions.",
    fabric: "Pure Gaji Silk",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Dry clean only. Do not wring. Store folded in muslin cloth.",
    price: "AUD 420",
    status: "in-stock",
    category: "saree",
    occasion: ["Wedding", "Festive"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p001-1.jpg",
      "images/p001-2.jpg",
      "images/p001-3.jpg",
      "images/p001-4.jpg",
    ],
    placeholderColor: "#8B1A1A",
    whatsappText: "Hi, I'm interested in the Crimson Gaji Silk Bandhani Saree from your collection."
  },
  {
    id: "p002",
    name: "Royal Blue Georgette Bandhani Dupatta",
    subtitle: "Pure Georgette · Borjaal Pattern",
    description: "Vibrant royal blue with classic white Borjaal dots. Lightweight georgette drape, perfect for casual and party styling.",
    fabric: "Pure Georgette",
    blouse: "N/A — Dupatta only",
    length: "2.5 metres",
    care: "Gentle hand wash in cold water. Do not bleach.",
    price: "AUD 180",
    status: "in-stock",
    category: "dupatta",
    occasion: ["Casual", "Party"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p002-1.jpg",
      "images/p002-2.jpg",
      "images/p002-3.jpg",
      "images/p002-4.jpg",
    ],
    placeholderColor: "#1A3A8B",
    whatsappText: "Hi, I'm interested in the Royal Blue Georgette Bandhani Dupatta from your collection."
  },
  {
    id: "p003",
    name: "Saffron Gharchola Bandhani Saree",
    subtitle: "Pure Gaji Silk · Gharchola Weave",
    description: "Traditional Gharchola weave with fine Bandhani work in warm saffron. A bridal staple in Gujarati weddings, rich in heritage significance.",
    fabric: "Pure Gaji Silk",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Dry clean only.",
    price: "AUD 580",
    status: "in-stock",
    category: "saree",
    occasion: ["Wedding", "Bridal"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p003-1.jpg",
      "images/p003-2.jpg",
      "images/p003-3.jpg",
      "images/p003-4.jpg",
    ],
    placeholderColor: "#E8832A",
    whatsappText: "Hi, I'm interested in the Saffron Gharchola Bandhani Saree from your collection."
  },
  {
    id: "p004",
    name: "Forest Green Silk Bandhani Dupatta",
    subtitle: "Modal Silk · Fine Dot Work",
    description: "Deep forest green with intricate fine-dot Bandhani pattern. Versatile dupatta for festive and semi-formal occasions.",
    fabric: "Modal Silk",
    blouse: "N/A — Dupatta only",
    length: "2.5 metres",
    care: "Dry clean recommended.",
    price: "AUD 220",
    status: "made-to-order",
    category: "dupatta",
    occasion: ["Festive"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p004-1.jpg",
      "images/p004-2.jpg",
      "images/p004-3.jpg",
      "images/p004-4.jpg",
    ],
    placeholderColor: "#1B5E20",
    whatsappText: "Hi, I'd like to enquire about a made-to-order Forest Green Silk Bandhani Dupatta."
  },
  {
    id: "p005",
    name: "Deep Maroon Bandhani Saree with Gota Border",
    subtitle: "Pure Gaji Silk · Gota Patti Border",
    description: "Rich maroon with traditional Bandhani work and an ornate Gota Patti border. An ideal wedding saree that commands attention.",
    fabric: "Pure Gaji Silk",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Dry clean only.",
    price: "AUD 650",
    status: "in-stock",
    category: "saree",
    occasion: ["Wedding"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p005-1.jpg",
      "images/p005-2.jpg",
      "images/p005-3.jpg",
      "images/p005-4.jpg",
    ],
    placeholderColor: "#8B1A1A",
    whatsappText: "Hi, I'm interested in the Deep Maroon Bandhani Saree with Gota Border from your collection."
  },
  {
    id: "p006",
    name: "Mustard Yellow Cotton Bandhani Dupatta",
    subtitle: "Pure Cotton · Classic Chunari Pattern",
    description: "Bright mustard yellow in breathable cotton with a classic Chunari Bandhani pattern. Perfect for Navratri and casual wear.",
    fabric: "Pure Cotton",
    blouse: "N/A — Dupatta only",
    length: "2.5 metres",
    care: "Machine wash cold, gentle cycle.",
    price: "AUD 120",
    status: "in-stock",
    category: "dupatta",
    occasion: ["Navratri", "Casual"],
    finishing: ["Roll Press", "Semi-Iron"],
    images: [
      "images/p006-1.jpg",
      "images/p006-2.jpg",
      "images/p006-3.jpg",
      "images/p006-4.jpg",
    ],
    placeholderColor: "#C8973A",
    whatsappText: "Hi, I'm interested in the Mustard Yellow Cotton Bandhani Dupatta from your collection."
  },
  {
    id: "p007",
    name: "Pink & Gold Bandhani Silk Saree",
    subtitle: "Khaddi Georgette · Banarasi Border",
    description: "Soft blush pink with gold Bandhani work and a heavy Banarasi woven border. A statement piece for receptions and sangeet.",
    fabric: "Khaddi Georgette",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Dry clean only.",
    price: "AUD 720",
    status: "made-to-order",
    category: "saree",
    occasion: ["Bridal", "Reception"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p007-1.jpg",
      "images/p007-2.jpg",
      "images/p007-3.jpg",
      "images/p007-4.jpg",
    ],
    placeholderColor: "#C2185B",
    whatsappText: "Hi, I'd like to enquire about a made-to-order Pink & Gold Bandhani Silk Saree."
  },
  {
    id: "p008",
    name: "Teal Bandhani Dupatta with Foil Work",
    subtitle: "Modal Silk · Gold Foil Detailing",
    description: "Striking teal with Bandhani dot pattern enhanced with hand-applied gold foil work. Exclusively finished by our in-house service.",
    fabric: "Modal Silk",
    blouse: "N/A — Dupatta only",
    length: "2.5 metres",
    care: "Dry clean only. Foil work is delicate.",
    price: "AUD 260",
    status: "in-stock",
    category: "dupatta",
    occasion: ["Party", "Festive"],
    finishing: ["Roll Press"],
    images: [
      "images/p008-1.jpg",
      "images/p008-2.jpg",
      "images/p008-3.jpg",
      "images/p008-4.jpg",
    ],
    placeholderColor: "#00695C",
    whatsappText: "Hi, I'm interested in the Teal Bandhani Dupatta with Foil Work from your collection."
  },
  {
    id: "p009",
    name: "Ivory & Gold Gharchola Saree",
    subtitle: "Pure Gaji Silk · Gharchola Weave · Bridal",
    description: "Pure ivory with delicate gold Bandhani dots in traditional Gharchola weave. The quintessential Gujarati bridal saree — timeless and deeply auspicious.",
    fabric: "Pure Gaji Silk",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Dry clean only.",
    price: "AUD 890",
    status: "made-to-order",
    category: "saree",
    occasion: ["Bridal"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p009-1.jpg",
      "images/p009-2.jpg",
      "images/p009-3.jpg",
      "images/p009-4.jpg",
    ],
    placeholderColor: "#9E8A5A",
    whatsappText: "Hi, I'd like to enquire about the made-to-order Ivory & Gold Gharchola Saree for a bridal occasion."
  },
  {
    id: "p010",
    name: "Peacock Blue Bandhani Saree",
    subtitle: "Modal Silk · Scattered Dot Pattern",
    description: "Vibrant peacock blue Modal Silk with evenly scattered fine Bandhani dots. Light, fluid, and perfect for festival and party wear.",
    fabric: "Modal Silk",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Gentle hand wash in cold water.",
    price: "AUD 480",
    status: "in-stock",
    category: "saree",
    occasion: ["Festival", "Party"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p010-1.jpg",
      "images/p010-2.jpg",
      "images/p010-3.jpg",
      "images/p010-4.jpg",
    ],
    placeholderColor: "#0277BD",
    whatsappText: "Hi, I'm interested in the Peacock Blue Bandhani Saree from your collection."
  },
  {
    id: "p011",
    name: "Magenta Bandhani Dupatta",
    subtitle: "Pure Georgette · Chunari Pattern",
    description: "Bold magenta georgette dupatta with classic Chunari Bandhani work. High-energy colour for Navratri and festive occasions.",
    fabric: "Pure Georgette",
    blouse: "N/A — Dupatta only",
    length: "2.5 metres",
    care: "Dry clean recommended.",
    price: "AUD 160",
    status: "in-stock",
    category: "dupatta",
    occasion: ["Casual", "Navratri"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p011-1.jpg",
      "images/p011-2.jpg",
      "images/p011-3.jpg",
      "images/p011-4.jpg",
    ],
    placeholderColor: "#AD1457",
    whatsappText: "Hi, I'm interested in the Magenta Bandhani Dupatta from your collection."
  },
  {
    id: "p012",
    name: "Deep Purple Silk Bandhani Saree",
    subtitle: "Pure Gaji Silk · Borjaal Lattice Pattern",
    description: "Deep royal purple with an intricate Borjaal lattice Bandhani pattern. A standout piece for weddings and receptions where you want to be remembered.",
    fabric: "Pure Gaji Silk",
    blouse: "Matching blouse piece included (0.8m)",
    length: "5.5 metres saree + 0.8m blouse",
    care: "Dry clean only.",
    price: "AUD 560",
    status: "made-to-order",
    category: "saree",
    occasion: ["Wedding", "Reception"],
    finishing: ["Roll Press", "Semi-Iron", "Crush"],
    images: [
      "images/p012-1.jpg",
      "images/p012-2.jpg",
      "images/p012-3.jpg",
      "images/p012-4.jpg",
    ],
    placeholderColor: "#4A148C",
    whatsappText: "Hi, I'd like to enquire about a made-to-order Deep Purple Silk Bandhani Saree."
  }
];
